In [3]:
!pip install opencv-contrib-python==3.4.2.16

In [4]:
import cv2
import pandas as pd
import numpy as np
import os

In [5]:
## helper functions ##
## gets file names for a particular type of trash, given indices
    ## input: waste category and indices
    ## output: file names 
def get_names(waste_type,indices):
    file_names = ["dataset-resized/"+waste_type+"/"+waste_type+str(i)+".jpg" for i in indices]
    return(file_names)    

## perform sift for image at image_name file location. Returns the SIFT descriptors
def sift_image(image_name):
    img = cv2.imread(image_name) #read image
    gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY) #normalize image to grayscale
    sift = cv2.xfeatures2d.SIFT_create() 
    kp, descriptors = sift.detectAndCompute(gray,None)
    return descriptors

In [87]:
waste_types = ['trash','cardboard','glass','metal','paper','plastic']

image_names = []
image_types = []
image_descriptors = []

# Perform SIFT for each image
for waste_index in range(0, len(waste_types)):
    waste_type = waste_types[waste_index]
    print(waste_type)
    source_folder = os.path.join('dataset-resized',waste_type)
    
    n = len(os.listdir(source_folder))
    full_set = list(range(1,n+1))
    
    for image_name in get_names(waste_type, full_set):
        image_names.append(image_name)
        image_types.append(waste_index)
        image_descriptors.append(sift_image(image_name))


trash
cardboard
glass
metal
paper
plastic


In [8]:
print(len(image_descriptors))

2527


In [23]:
print(image_descriptors[4])

(737, 128)


In [89]:
import json 

ind_to_delete = []
for i in range(0, len(image_names)):
    if image_descriptors[i] is None:
        ind_to_delete.insert(0,i)
        
for i in ind_to_delete:
    print('Deleted ' + image_names[i])
    del image_names[i]
    del image_types[i]
    del image_descriptors[i]


Deleted dataset-resized/plastic/plastic2.jpg
Deleted dataset-resized/paper/paper539.jpg
Deleted dataset-resized/paper/paper385.jpg
Deleted dataset-resized/cardboard/cardboard387.jpg
Deleted dataset-resized/cardboard/cardboard110.jpg
Deleted dataset-resized/cardboard/cardboard86.jpg


In [91]:
temp = []
for desc in image_descriptors:
    temp.append(json.dumps(desc.tolist()))
    
image_descriptors = temp
image_descriptors

In [94]:
image_descriptors[0]

'[[32.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 9.0, 172.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 18.0, 172.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 7.0, 4.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 3.0, 50.0, 2.0, 0.0, 0.0, 0.0, 0.0, 0.0, 10.0, 172.0, 6.0, 0.0, 0.0, 0.0, 0.0, 0.0, 48.0, 172.0, 4.0, 0.0, 0.0, 0.0, 0.0, 0.0, 22.0, 10.0, 2.0, 0.0, 0.0, 0.0, 0.0, 1.0, 4.0, 37.0, 27.0, 4.0, 0.0, 0.0, 0.0, 0.0, 1.0, 172.0, 93.0, 0.0, 0.0, 0.0, 0.0, 0.0, 5.0, 172.0, 29.0, 0.0, 0.0, 0.0, 0.0, 2.0, 11.0, 7.0, 1.0, 0.0, 0.0, 0.0, 0.0, 5.0, 8.0, 17.0, 13.0, 2.0, 0.0, 0.0, 0.0, 1.0, 7.0, 172.0, 74.0, 0.0, 0.0, 0.0, 0.0, 0.0, 3.0, 172.0, 39.0, 0.0, 0.0, 0.0, 0.0, 1.0, 7.0, 5.0, 0.0, 0.0, 0.0, 0.0, 1.0, 6.0, 7.0], [101.0, 18.0, 3.0, 10.0, 11.0, 6.0, 12.0, 49.0, 25.0, 4.0, 1.0, 68.0, 126.0, 2.0, 1.0, 8.0, 100.0, 1.0, 0.0, 21.0, 82.0, 5.0, 3.0, 67.0, 55.0, 2.0, 7.0, 32.0, 14.0, 17.0, 5.0, 39.0, 14.0, 1.0, 0.0, 6.0, 50.0, 30.0, 65.0, 68.0, 17.0, 5.0, 3.0, 110.0, 126.0, 42.0, 5.0, 8.0, 126.0, 23.0, 6.0, 41.0, 43.0, 8.0, 3.0, 65.0, 42.0,

In [95]:
df = pd.DataFrame()
df['name'] = image_names
df['type'] = image_types
df['descriptor'] = image_descriptors
df.head()

name  type  \
0  dataset-resized/trash/trash1.jpg     0   
1  dataset-resized/trash/trash2.jpg     0   
2  dataset-resized/trash/trash3.jpg     0   
3  dataset-resized/trash/trash4.jpg     0   
4  dataset-resized/trash/trash5.jpg     0   

                                          descriptor  
0  [[32.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 9.0, 172...  
1  [[133.0, 64.0, 1.0, 0.0, 0.0, 3.0, 12.0, 18.0,...  
2  [[0.0, 0.0, 0.0, 3.0, 20.0, 12.0, 4.0, 3.0, 47...  
3  [[27.0, 133.0, 147.0, 0.0, 0.0, 0.0, 0.0, 1.0,...  
4  [[4.0, 42.0, 42.0, 0.0, 1.0, 35.0, 59.0, 12.0,...

In [74]:
import json
x = json.dumps(image_descriptors[0].tolist())
y = json.loads(x)
y

[[32.0,
  1.0,
  1.0,
  0.0,
  0.0,
  0.0,
  0.0,
  9.0,
  172.0,
  1.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  18.0,
  172.0,
  1.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  7.0,
  4.0,
  0.0,
  0.0,
  0.0,
  0.0,
  1.0,
  1.0,
  3.0,
  50.0,
  2.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  10.0,
  172.0,
  6.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  48.0,
  172.0,
  4.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  22.0,
  10.0,
  2.0,
  0.0,
  0.0,
  0.0,
  0.0,
  1.0,
  4.0,
  37.0,
  27.0,
  4.0,
  0.0,
  0.0,
  0.0,
  0.0,
  1.0,
  172.0,
  93.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  5.0,
  172.0,
  29.0,
  0.0,
  0.0,
  0.0,
  0.0,
  2.0,
  11.0,
  7.0,
  1.0,
  0.0,
  0.0,
  0.0,
  0.0,
  5.0,
  8.0,
  17.0,
  13.0,
  2.0,
  0.0,
  0.0,
  0.0,
  1.0,
  7.0,
  172.0,
  74.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  3.0,
  172.0,
  39.0,
  0.0,
  0.0,
  0.0,
  0.0,
  1.0,
  7.0,
  5.0,
  0.0,
  0.0,
  0.0,
  0.0,
  1.0,
  6.0,
  7.0],
 [101.0,
  18.0,
  3.0,
  10.0,
  11.0,
  6.0,
  12.0,
  49.0,
  25.0,


In [96]:
df.to_csv('image_sift.csv', header=True, index=False) 

In [59]:
from sklearn.cluster import KMeans

d_list = image_descriptors[0]
first = True
for i in range(1, len(image_descriptors)):
    if not first:
        print(i)
        d_list = np.concatenate((d_list, image_descriptors[1]))
    else:
        first = False
d_list.shape


2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
277
27

1862
1863
1864
1865
1866
1867
1868
1869
1870
1871
1872
1873
1874
1875
1876
1877
1878
1879
1880
1881
1882
1883
1884
1885
1886
1887
1888
1889
1890
1891
1892
1893
1894
1895
1896
1897
1898
1899
1900
1901
1902
1903
1904
1905
1906
1907
1908
1909
1910
1911
1912
1913
1914
1915
1916
1917
1918
1919
1920
1921
1922
1923
1924
1925
1926
1927
1928
1929
1930
1931
1932
1933
1934
1935
1936
1937
1938
1939
1940
1941
1942
1943
1944
1945
1946
1947
1948
1949
1950
1951
1952
1953
1954
1955
1956
1957
1958
1959
1960
1961
1962
1963
1964
1965
1966
1967
1968
1969
1970
1971
1972
1973
1974
1975
1976
1977
1978
1979
1980
1981
1982
1983
1984
1985
1986
1987
1988
1989
1990
1991
1992
1993
1994
1995
1996
1997
1998
1999
2000
2001
2002
2003
2004
2005
2006
2007
2008
2009
2010
2011
2012
2013
2014
2015
2016
2017
2018
2019
2020
2021
2022
2023
2024
2025
2026
2027
2028
2029
2030
2031
2032
2033
2034
2035
2036
2037
2038
2039
2040
2041
2042
2043
2044
2045
2046
2047
2048
2049
2050
2051
2052
2053
2054
2055
2056
2057
2058
2059
2060
2061


(397235, 128)

In [63]:
kmeans = KMeans(n_clusters = 800)
kmeans.fit(d_list)


KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
       n_clusters=800, n_init=10, n_jobs=None, precompute_distances='auto',
       random_state=None, tol=0.0001, verbose=0)

In [ ]:
preprocessed_image = []
for image_descriptor in image_descriptors:
      if (descriptor is not None):
          histogram = build_histogram(descriptor, kmeans)
          preprocessed_image.append(histogram)

In [46]:
# d_list = np.append(image_descriptors[0], image_descriptors[1])
d_list = np.concatenate((d_list, image_descriptors[1]))
print(d_list.shape)

(1595, 128)


In [60]:
np.savetxt('all_descriptors.txt', d_list, fmt='%f')

In [61]:
b = np.loadtxt('all_descriptors.txt', dtype=float)

In [62]:
print(b)

[[ 32.   1.   1. ...   1.   6.   7.]
 [101.  18.   3. ...  75.  41.  21.]
 [  3.   0.  39. ...   0.   5.  15.]
 ...
 [  0.   1.   7. ...   1.   0.   3.]
 [  0.   0.   4. ...   0.   1.  75.]
 [133.  53.  11. ...   0.   0.   0.]]
